# Generated by Django 3.2.5 on 2021-07-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210717_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='clothes',
        ),
    ]
